version: '2'

services:
  webparrot:
    restart: 'always'
    build: '.'
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ~/certs:/certs
    environment:
      - PRODUCTION_ENV=true
      - PRODUCTION_DOMAIN=parrot.postapp.biz